#! /usr/bin/env python
#encoding: utf-8

# def configure(cnf):
#   cnf.recurse(src)
# def configure(cnf):
#   cnf.recurse(include)

# def sim_source(cnf):
#   cnf.recurse(src)
# def sim_source(cnf):
#   cnf.recurse(include)
