// Generated by Cadence Encounter(R) RTL Compiler RC14.28 - v14.20-s067_1
tclmode
set env(RC_VERSION) "RC14.28 - v14.20-s067_1"
vpxmode
set dofile abort exit
usage -auto -elapse
set log file fv/FPU_top_level/rtl_to_g1.log -replace
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
vpxmode
tclmode
set env(CDN_SYNTH_ROOT) /package/eda/cadence/RC142/tools
set CDN_SYNTH_ROOT /package/eda/cadence/RC142/tools
vpxmode
tclmode
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set hdl options -VERILOG_INCLUDE_DIR "sep:src:cwd"
set undriven signal Z -golden

add search path -library /package/asicfab/MITLL_90_Dec2019/MITLL90_STDLIB_8T/2019.12.20
read library -statetable -liberty -both  \
	/package/asicfab/MITLL_90_Dec2019/MITLL90_STDLIB_8T/2019.12.20/MITLL90_STDLIB_8T.tt1p2v25c.lib

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/FPU_top_level.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/FPU_top_level.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/adder_8b.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/adder_8b.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/mul_26b.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/mul_26b.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/left_shift.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/left_shift.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/subtract.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/subtract.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/rounder.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/rounder.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/rounder_sub.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/rounder_sub.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/int_compare.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/int_compare.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/right_shift.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/right_shift.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/u_to_s.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/u_to_s.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/adder_26b.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/adder_26b.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/s_to_u.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/s_to_u.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step1.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step1.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step2.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step2.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step3.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/ADD_step3.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/MUL_step1.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/MUL_step1.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/MUL_step2.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/MUL_step2.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step1.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step1.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step2.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step2.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/sub_26b.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/sub_26b.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/sign_determine.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/sign_determine.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/c_to_cp.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/c_to_cp.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step3.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/SUB_step3.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/int_comparesub.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/int_comparesub.sv
}
vpxmode

delete search path -all
add search path -design ./src ./include ./tb_include
tclmode
if {$ver < 13.10} {
vpx read design -enumconstraint  -define SYNTHESIS  -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/determine_frac_status.sv
} else {
vpx read design -enumconstraint  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab -systemverilog \
	/local/scratch/a/socet19/RISCVBusiness/source_code/Floating_Point_Unit/source/determine_frac_status.sv
}
vpxmode

elaborate design -golden -root FPU_top_level -rootonly

tclmode
if {$ver < 13.10} {
vpx read design -verilog -revised -lastmod -noelab \
	-unzip fv/FPU_top_level/g1.v.gz
} else {
vpx read design -verilog95 -revised -lastmod -noelab \
	-unzip fv/FPU_top_level/g1.v.gz
}
vpxmode

elaborate design -revised -root FPU_top_level

tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver < 13.10} {
vpx substitute blackbox model -golden
}
vpxmode
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
set parallel option -threads 4 -license xl -norelease_license
set analyze option -auto

write hier_compare dofile fv/FPU_top_level/hier_rtl_to_g1.do \
	-noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath  -verbose"
run hier_compare fv/FPU_top_level/hier_rtl_to_g1.do -dynamic_hierarchy
// report hier_compare result -dynamicflattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -NONequivalent] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
exit -force
