onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/clk
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/nrst
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/floating_point1
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/floating_point2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frm
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/funct7
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/floating_point_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/flags
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frm2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frm3
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/funct7_2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/funct7_3
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sign_shifted
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sign_shifted_minus
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frac_shifted
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frac_shifted_minus
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sign_not_shifted
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sign_not_shifted_minus
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frac_not_shifted
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frac_not_shifted_minus
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/exp_max
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/exp_max_minus
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_sign1
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_sign2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_exp1
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_exp2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/product
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_carry_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/step1_to_step2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/nxt_step1_to_step2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/add_sign_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/add_sum
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/add_carry_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/add_exp_max
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/minus_sign_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/minus_sum
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/minus_carry_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/minus_exp_max
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/cmp_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/cmp_out_det
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/fp1_sign
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/fp1_frac
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/fp2_sign
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/fp2_frac
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_sign_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sum_exp
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_ovf
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/mul_unf
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/inv
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/inv2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/inv3
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/step2_to_step3
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/nxt_step2_to_step3
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/exp_determine
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/bothnegsub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/bothpossub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/n1p2
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/n1p2r
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/signout
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/same_compare
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/shifted_check_allone
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/shifted_check_onezero
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/unsigned_exp_diff
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/frac_same
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/wm
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/ovf
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/unf
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/inexact
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/ovf_sub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/unf_sub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/inexact_sub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/flag_add
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/flag_sub
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/sum_init
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/outallone
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/outallzero
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/o
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/negmul_floating_point_out
add wave -noupdate -expand -group dut -radix binary /tb_FPU_top_level/DUT/add_floating_point_out
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/clk
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/nrst
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/floating_point1
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/floating_point2
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/frm
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/floating_point_out
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/funct7
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/flags
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/result_real
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/result_binary
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/fp1_real
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/fp2_real
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/fp_out_real
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/fp_exp
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/fp_frac
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/i
add wave -noupdate -expand -group top_level -radix binary /tb_FPU_top_level/j
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/fp1_frac1
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/fp2_frac2
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/frac_same
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/temp_fp1_frac1
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/temp_fp2_frac2
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/diff_frac1_frac2
add wave -noupdate -expand -group determine_Frac -radix binary /tb_FPU_top_level/DUT/determine_frac_status/diff_determine
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/exp1
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/exp2
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/u_diff
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/cmp_out
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/same_compare
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/u_exp1
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/u_exp2
add wave -noupdate -expand -group CMP_EXPONENT -radix binary /tb_FPU_top_level/DUT/cmp_exponent/diff
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/cmp_out
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/same_compare
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/frac_same
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/floating_point1
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/floating_point2
add wave -noupdate -expand -group sign_determine -radix binary /tb_FPU_top_level/DUT/sign_determine/signout
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/floating_point1_in
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/floating_point2_in
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/sign_shifted
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/frac_shifted
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/sign_not_shifted
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/frac_not_shifted
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/exp_max
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/unsigned_exp_diff
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/cmp_out
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/floating_point_shift
add wave -noupdate -expand -group add_satep1 -radix binary /tb_FPU_top_level/DUT/addStep1/floating_point_not_shift
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/bothnegsub
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point1_in
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point2_in
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/sign_shifted
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/frac_shifted
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/sign_not_shifted
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/frac_not_shifted
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/exp_max
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/cmp
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/unsigned_exp_diff
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point1_in_temp
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point2_in_temp
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/cmp_out
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point_shift
add wave -noupdate -expand -group sub_step1 -radix binary /tb_FPU_top_level/DUT/substep1/floating_point_not_shift
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/fp1_in
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/fp2_in
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/sign1
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/sign2
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/exp1
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/exp2
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/product
add wave -noupdate -expand -group mul_step1 -radix binary /tb_FPU_top_level/DUT/mulStep1/carry_out
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/frac1
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/sign1
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/frac2
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/sign2
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/exp_max_in
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/sign_out
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/sum
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/carry_out
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/exp_max_out
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/frac1_signed
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/frac2_signed
add wave -noupdate -expand -group add_step2 -radix binary /tb_FPU_top_level/DUT/add_step2/sum_signed
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/shifted_check_onezero
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/n1p2r
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/bothnegsub
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/fp1
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/fp2
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac1
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sign1
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac2
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sign2
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/exp_max_in
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/exp_determine
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/bothpossub
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/n1p2
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/cmp_out
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sign_out
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sum
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/carry_out
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/exp_max_out
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/outallone
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/outallzero
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/wm
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sum_init
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac1_signed
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac2_signed
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/sum_signed
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac2_complement
add wave -noupdate -expand -group sub_step2 -radix binary /tb_FPU_top_level/DUT/sub_step2/frac2_signedout
add wave -noupdate -expand -group u_to_s -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_signed1/sign
add wave -noupdate -expand -group u_to_s -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_signed1/frac_unsigned
add wave -noupdate -expand -group u_to_s -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_signed1/frac_signed
add wave -noupdate -expand -group c_to_cp -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_complement/frac2_input
add wave -noupdate -expand -group c_to_cp -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_complement/frac2_signedin
add wave -noupdate -expand -group c_to_cp -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_complement/frac2_output
add wave -noupdate -expand -group c_to_cp -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_complement/frac2_signedout
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/n1p2r
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/shifted_check_onezero
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/fp1
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/fp2
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/cmp_out
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/frac1
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/frac2
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/frac1_s
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/frac2_s
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/n1p2
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/bothpossub
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/sum
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/ovf
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/outallone
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/outallzero
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/wm
add wave -noupdate -expand -group sub_signed_f -radix binary /tb_FPU_top_level/DUT/sub_step2/sub_signed_fracs/sum_init
add wave -noupdate -expand -group s_to_us -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_unsigned/frac_signed
add wave -noupdate -expand -group s_to_us -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_unsigned/sign
add wave -noupdate -expand -group s_to_us -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_unsigned/frac_unsigned
add wave -noupdate -expand -group s_to_us -radix binary /tb_FPU_top_level/DUT/sub_step2/change_to_unsigned/rfrac_signed
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/sign1
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/sign2
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/exp1
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/exp2
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/sign_out
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/sum_exp
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/ovf
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/unf
add wave -noupdate -expand -group mul_step2 -radix binary /tb_FPU_top_level/DUT/mul_step2/carry
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/sum_init
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/unsigned_exp_diff
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/n1p2r
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/wm
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/clk
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/nrst
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/frac_shifted_minus
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/outallzero
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/outallone
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/same_compare
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/bothnegsub
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/cmp_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/floating_point1
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/floating_point2
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/function_mode
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/ovf_in
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/unf_in
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/dz
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/inv
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/frm
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/exponent_max_in
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/sign_in
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/frac_in
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/carry_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/shifted_check_allone
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/shifted_check_onezero
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/before_floating_point_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/ovf
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/unf
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/inexact
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/sign
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/exponent
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/frac
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/shifted_frac
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/shifted_amount
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/exp_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/temp_sign
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/dummy_floating_point_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/fp_option
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/hold_value
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/rounded_frac
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/round_this
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/log_de
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/round_out
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/buf_determine
add wave -noupdate -expand -group sub_step3 -radix binary /tb_FPU_top_level/DUT/sub_step3/round_flag
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/sum_init
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/clk
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/nrst
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/unsigned_exp_diff
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/frac_in
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/shifted_frac
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/n1p2r
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/wm
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/shifted_amount
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/buf_determine
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/frac_shifted_minus
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/outallzero
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/outallone
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/same_compare
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/bothnegsub
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/cmp_out
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/fp1
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/fp2
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/frm
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/sign
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/exp_in
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/fraction
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/carry_out
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/shifted_check_allone
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/shifted_check_onezero
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/round_out
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/rounded
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/sol_frac
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/round_amount
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/temp_round_out
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/temp_fraction
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/temp_exp
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/mod
add wave -noupdate -expand -group rounder -radix binary /tb_FPU_top_level/DUT/sub_step3/ROUND/flag_inexact
add wave -noupdate -expand -group left_shift -radix binary /tb_FPU_top_level/DUT/sub_step3/shift_left/fraction
add wave -noupdate -expand -group left_shift -radix binary /tb_FPU_top_level/DUT/sub_step3/shift_left/result
add wave -noupdate -expand -group left_shift -radix binary /tb_FPU_top_level/DUT/sub_step3/shift_left/shifted_amount
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/frm
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/sign
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/exp_in
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/fraction
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/round_out
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/rounded
add wave -noupdate -expand -group round -radix binary /tb_FPU_top_level/DUT/add_step3/ROUND/round_amount
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/exp1
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/shifted_amount
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/result
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/u_exp1
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/u_shifted_amount
add wave -noupdate -expand -group sub -radix binary /tb_FPU_top_level/DUT/add_step3/SUB/u_result
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/function_mode
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/floating_point1
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/floating_point2
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/ovf_in
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/unf_in
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/dz
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/inv
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/frm
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/exponent_max_in
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/sign_in
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/frac_in
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/carry_out
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/add_floating_point_out
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/ovf
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/unf
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/inexact
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/sign
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/exponent
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/frac
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/dummy_floating_point_out
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/exp_minus_shift_amount
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/shifted_frac
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/shifted_amount
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/exp_out
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/round_this
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/fp_option
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/round_out
add wave -noupdate -expand -group add_step3 -radix binary /tb_FPU_top_level/DUT/add_step3/round_flag
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {13970000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 235
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {13960434 ps} {13981678 ps}
